//------------------------------------------------------------------------------
// <auto-generated>
// DO NOT MODIFY! Automatically generated via updateLocalizationClass.py script.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Avalonia;
using Avalonia.Controls;

namespace NandroidDataConverter;

public class Localization
{
    public static Dictionary<string, string> Localizations { get; set; } = new Dictionary<string, string>();
    public static string FilesLocation
    {
        get
        {
            return Localizations.GetValueOrDefault("filesLocation", "filesLocation");
        }
    }
    public static string OutputFilesLocation
    {
        get
        {
            return Localizations.GetValueOrDefault("outputFilesLocation", "outputFilesLocation");
        }
    }
    public static string Choose
    {
        get
        {
            return Localizations.GetValueOrDefault("choose", "choose");
        }
    }
    public static string Convert
    {
        get
        {
            return Localizations.GetValueOrDefault("convert", "convert");
        }
    }
    public static string ConversionResult
    {
        get
        {
            return Localizations.GetValueOrDefault("conversionResult", "conversionResult");
        }
    }
    public static string Processed
    {
        get
        {
            return Localizations.GetValueOrDefault("processed", "processed");
        }
    }
    public static string ProcessedSmsMessage_one
    {
        get
        {
            return Localizations.GetValueOrDefault("processedSmsMessage_one", "processedSmsMessage_one");
        }
    }
    public static string ProcessedSmsMessage_other
    {
        get
        {
            return Localizations.GetValueOrDefault("processedSmsMessage_other", "processedSmsMessage_other");
        }
    }
    public static string ProcessedContacts_one
    {
        get
        {
            return Localizations.GetValueOrDefault("processedContacts_one", "processedContacts_one");
        }
    }
    public static string ProcessedContacts_other
    {
        get
        {
            return Localizations.GetValueOrDefault("processedContacts_other", "processedContacts_other");
        }
    }
    public static string ProcessedCalls_one
    {
        get
        {
            return Localizations.GetValueOrDefault("processedCalls_one", "processedCalls_one");
        }
    }
    public static string ProcessedCalls_other
    {
        get
        {
            return Localizations.GetValueOrDefault("processedCalls_other", "processedCalls_other");
        }
    }
    public static string SelectFolder
    {
        get
        {
            return Localizations.GetValueOrDefault("selectFolder", "selectFolder");
        }
    }
    public static string ContentType
    {
        get
        {
            return Localizations.GetValueOrDefault("contentType", "contentType");
        }
    }
    public static string SmsMessages
    {
        get
        {
            return Localizations.GetValueOrDefault("smsMessages", "smsMessages");
        }
    }
    public static string Contacts
    {
        get
        {
            return Localizations.GetValueOrDefault("contacts", "contacts");
        }
    }
    public static string CallLog
    {
        get
        {
            return Localizations.GetValueOrDefault("callLog", "callLog");
        }
    }
    public static string FileMenu
    {
        get
        {
            return Localizations.GetValueOrDefault("fileMenu", "fileMenu");
        }
    }
    public static string ExitMenu
    {
        get
        {
            return Localizations.GetValueOrDefault("exitMenu", "exitMenu");
        }
    }
    public static string HelpMenu
    {
        get
        {
            return Localizations.GetValueOrDefault("helpMenu", "helpMenu");
        }
    }
    public static string AboutMenu
    {
        get
        {
            return Localizations.GetValueOrDefault("aboutMenu", "aboutMenu");
        }
    }
    public static string License
    {
        get
        {
            return Localizations.GetValueOrDefault("license", "license");
        }
    }
    public static string Libraries
    {
        get
        {
            return Localizations.GetValueOrDefault("libraries", "libraries");
        }
    }
    public static string AboutDescription
    {
        get
        {
            return Localizations.GetValueOrDefault("aboutDescription", "aboutDescription");
        }
    }
    public static string Close
    {
        get
        {
            return Localizations.GetValueOrDefault("close", "close");
        }
    }
}